### ISSUE TITLE
A public key can be locked by an attacker

### ISSUE THREAD

**Issue by DurandA** [FlurinT/MT#9]
An attacker can lock public keys of victims by registering them first. This can even happen if the attacker doesn't have prior knowledge of the public key (out-of-band): one can listen to staging transaction and create an _addKey_ transaction with the same keyHash with highter priority (e.g. with higher transaction fees).

https://github.com/FlurinT/MT/blob/c262110f57f53069c4df44231d0f3bc836c25e72/DPKI/contracts/DPKI.sol#L8

**Comment by FlurinT** [comment]
attacker needs to possess the according private key to add the key

**Comment by DurandA** [comment]
@FlurinT This is not entirely fixed. There is no binding of the _keyHash_ to the public key so an attacker can register an arbitrary _keyHash_ with any public key _Q_. My recommended fix is to compute the _keyHash_ on the smart contract directly (you need to compute it to check its validity anyway).
